@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWRlOTlhMzBiNWI2YjUyMTVlN2Y4MTciLCJlbWFpbCI6ImFhYTFAZ2dnLmNvbSIsImlhdCI6MTc3NjI0NTg0NSwiZXhwIjoxNzc2MjQ5NDQ1fQ.UxJ4PygevQusOA_e2yVxEgRyO6ZPpbmt50jpd1VS9_E
## Users API

### Create User

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Frank Miller",
    "email": "test3@ggg.com"
}

### Get Auth token
POST http://localhost:3000/users/auth
Content-Type: application/json

{
    "email": "aaa1@ggg.com"
}

## Products API

### Create Product

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Laptop Lenovo ThinkPad X1",
    "price": 1109.00
}

### Orders

POST http://localhost:3000/orders
Content-Type: application/json
Authorization: {{token}}

{
    "userId": "69de99a30b5b6b5215e7f817",
    "items": [
     {
        "productId": "69dbe9f9a6a748ae723329ab",
        "quantity": 1
     }]
}

###
GET http://localhost:3000/orders/69df58cf0f1cdfd19bf7cbe7
Content-Type: application/json
Authorization: {{token}}